apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: haproxy
  project: default
  source:
    repoURL: ssh://git@host.minikube.internal:2222/test-org/argo-cd-repo.git
    path: charts/haproxy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
