argo-cd:
  server:
    extraArgs:
      - --insecure

    ingress:
      enabled: true
      ingressClassName: haproxy
      hostname: argo.kamuridesu.com

  configs:
    ssh:
      knownHosts: |
        [host.minikube.internal]:2222 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLr+5yNJzDWCnQeNtNfscP0qnmsFff1rCAdsXViJsw0zLdGdqAYMYZrlY4aVSXoiTSqA5GcTY3U+Ct2mpNlHZMs=
        [host.minikube.internal]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPT2F1qD/K2MGrX8Q1lNOuQRMGN1XQyXfFM6iFZBH2B5UtL4mvt8ZRbTTiutDWHK1J5QdZLMG84wG2HAcYBYDjDuBOCtR5fgeuIx7O+3vajm+ar/Wm9Qkk7zZYyPSk//nilDUxngyWPFJFdeMIVmVUEuZ++/5qJz96Oxdsvk8BMlO9sbahJ1skt6r3ylfCqPY3MP7v3ZzJLo9jye7DUVgpT9O4h985oNyl7lEgCOkF3Wp9q96UEsEIw1kYS/zlwU2v7f9d5gzk48oBTodRKS7cM9KBVYQoOHAPxmEWsfFE9kJnYSQZZtCBUW+T9lVCarZk5LdXbFQkDP3fA1C5XlGX6RcZwkhSC61zevHG4dxhaneVZQdvCBA895mLqmLoOqJVvfIvSXbH/j3BNZBowmueU+ZavDLSoyZjoCDwgwEPZJw/Ka7lq3R5pjH+dOLtY8EGxI8L/cznL8i1CLA7bXhxIz6kYclC9Kt2bOtKMw8y5b7lRUj2VichSvpwwS6Y1Tk=
        [host.minikube.internal]:2222 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICqMPKLGAR4eArYQW0q3nRTB6m4cLsXg6lxBCAcIC+Bp

    secret:
      createSecret: true

    credentialTemplates:
      forgejo-creds:
        url: ssh://git@host.minikube.internal:2222
        sshPrivateKey: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACBtcqliT4Fwm/odyR5KNcd1XH55n6zugBUIfLg0XVsfuwAAAJhmwlOGZsJT
          hgAAAAtzc2gtZWQyNTUxOQAAACBtcqliT4Fwm/odyR5KNcd1XH55n6zugBUIfLg0XVsfuw
          AAAEDeRg1+vfi9+scZltFrGP2ULSm95RDpu6YkyToMUioRwG1yqWJPgXCb+h3JHko1x3Vc
          fnmfrO6AFQh8uDRdWx+7AAAAD2thbXVyaUBhcnRpeGJveAECAwQFBg==
          -----END OPENSSH PRIVATE KEY-----

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, /ArgoCDAdmins, role:admin
