argo-cd:
  server:
    extraArgs:
      - --insecure

    ingress:
      enabled: true
      ingressClassName: haproxy
      hostname: argo.kamuridesu.com

  configs:
    ssh:
      knownHosts: |
        [host.minikube.internal]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmjQn61PG0nNTx70CukyP1AlvE91SOgURRwu0RU8ycGB+CwIGRn3LXRfnb6/2EpMtzcHwgKhLYfxa1tdhMnqbztBxQH8PIIC533RAYJCeszdKtbQp+q1v3s/XSVy8qYhS3Vk1oyby8KbvFcwsU213Eiithr4VhhXCJxJcKB25ngXPdaWmtwYUzcfkR0ykkGE0S/ZKSEYC6DThE4k8CZoRVYcxOcTctZ043cFMy0EOpCB3KC/BI4sthomm6AT8g6yxVBk4ipCS4WimNeAZiqO+cc1udSH9qYmrdKrOUsLiq5S0s36CxDOUXZLvxgQNzVEZZB/vLLqvYHjZH4nFgeb9GPm3T2WJ091d9FqoUH5KBFCh4qY9HYqSnkxeWCLtHflcclgbqrCs53l2UIyODQth5P5l0LjYXAeAltWpAJine6ZcDuvghHLxt1StnoO9JzhHWr7M3udASICsLXoBdpHWD3775BSIFLcY2MIw3nkxIgERdBgpn4DLEBr2wZ5HlVU8=
        [host.minikube.internal]:2222 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCr1RNwOXPpMfNH6XOdwHITkDitDnzuEZ/neX4/NFkB3PUCCzhCurnDpZks1GZnGD9rZrVoITRCJDfmacz3ZXa0=
        [host.minikube.internal]:2222 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOZagmB5ZQXq+hvVdo42zGBwJK8r5vP6sL9M9JklqwiA

    secret:
      createSecret: true

    credentialTemplates:
      forgejo-creds:
        url: ssh://git@host.minikube.internal:2222
        sshPrivateKey: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACBtcqliT4Fwm/odyR5KNcd1XH55n6zugBUIfLg0XVsfuwAAAJhmwlOGZsJT
          hgAAAAtzc2gtZWQyNTUxOQAAACBtcqliT4Fwm/odyR5KNcd1XH55n6zugBUIfLg0XVsfuw
          AAAEDeRg1+vfi9+scZltFrGP2ULSm95RDpu6YkyToMUioRwG1yqWJPgXCb+h3JHko1x3Vc
          fnmfrO6AFQh8uDRdWx+7AAAAD2thbXVyaUBhcnRpeGJveAECAwQFBg==
          -----END OPENSSH PRIVATE KEY-----

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, /ArgoCDAdmins, role:admin
